import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const data = cookieStore.get("token")?.value || "";

  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${inter.className}`}
        style={{ background: "whitesmoke" }}
      >
        <Header token={data} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
